controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    rover_base_control:
      type: diff_drive_controller/DiffDriveController

rover_base_control:
  ros__parameters:
    left_wheel_names:
      - Rueda_dealntera_iz
      - Rueda_trasera1_iz
    right_wheel_names:
      - Rueda_dealntera_der
      - Rueda_trasera1_der
    wheel_separation: 2.0
    wheel_radius: 0.40
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: -1.0
    odom_frame_id: /odom
    base_frame_id: /base_footprint
    cmd_vel_timeout: 0.1
    use_stamped_vel: false
    publish_rate: 50.0
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
        has_jerk_limits: false
        max_jerk: 0.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 6.0
        has_jerk_limits: false
        max_jerk: 0.0